# Day 4

- Missing Values
- Type Casting
- Dealing with Duplicates
- Feature Engineering (make derived columns with .apply)
- Reshape data using pivot_table or groupby or agg
- Mapping a column to a category label (merge original df with another)

In [250]:
import pandas as pd

df = pd.read_csv("../Day-3/pakistan_economic_indicators_2000_2025.csv")
df.head()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.9,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.0,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.1,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.7,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.4,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s

In [251]:
df.columns

Index(['year', 'gdp_usd_bn', 'gdp_growth_pct', 'gdp_per_capita_usd',
       'inflation_cpi_pct', 'unemployment_pct', 'remittances_usd_bn',
       'exports_usd_bn', 'imports_usd_bn', 'trade_balance_usd_bn',
       'forex_reserves_usd_bn', 'policy_rate_pct', 'pkr_per_usd',
       'public_debt_gdp_pct', 'current_account_usd_bn', 'fdi_inflows_usd_bn',
       'population_mn', 'literacy_rate_pct', 'agriculture_gdp_pct',
       'services_gdp_pct', 'industry_gdp_pct', 'tax_revenue_gdp_pct',
       'mobile_per_100', 'imf_program_active', 'key_events',
       'remittances_gdp_pct', 'exports_gdp_pct', 'imports_gdp_pct',
       'fdi_gdp_pct', 'gdp_growth_category', 'inflation_category', 'decade'],
      dtype='str')

In [252]:
df.dtypes

year                        int64
gdp_usd_bn                float64
gdp_growth_pct            float64
gdp_per_capita_usd          int64
inflation_cpi_pct         float64
unemployment_pct          float64
remittances_usd_bn        float64
exports_usd_bn            float64
imports_usd_bn            float64
trade_balance_usd_bn      float64
forex_reserves_usd_bn     float64
policy_rate_pct           float64
pkr_per_usd               float64
public_debt_gdp_pct       float64
current_account_usd_bn    float64
fdi_inflows_usd_bn        float64
population_mn             float64
literacy_rate_pct         float64
agriculture_gdp_pct       float64
services_gdp_pct          float64
industry_gdp_pct          float64
tax_revenue_gdp_pct       float64
mobile_per_100            float64
imf_program_active          int64
key_events                    str
remittances_gdp_pct       float64
exports_gdp_pct           float64
imports_gdp_pct           float64
fdi_gdp_pct               float64
gdp_growth_category           str
inflation_category            str
decade                        str
dtype: object

## Handling Missing Values
---

- its explicitly stated to use the dataset from day 3 but that one has no missing values or duplicates or wrongly type casted columns, so I will just focus on learning each step generally


- I will go through diff methods of finds and printing out missing values and also go through dealing with them (drop them or fill them up). Will put tny comments in each cell

In [253]:
# to find exact empty cells
df.isna()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [254]:
# find total missing cells in each column
df.isna().sum()

year                      0
gdp_usd_bn                0
gdp_growth_pct            0
gdp_per_capita_usd        0
inflation_cpi_pct         0
unemployment_pct          0
remittances_usd_bn        0
exports_usd_bn            0
imports_usd_bn            0
trade_balance_usd_bn      0
forex_reserves_usd_bn     0
policy_rate_pct           0
pkr_per_usd               0
public_debt_gdp_pct       0
current_account_usd_bn    0
fdi_inflows_usd_bn        0
population_mn             0
literacy_rate_pct         0
agriculture_gdp_pct       0
services_gdp_pct          0
industry_gdp_pct          0
tax_revenue_gdp_pct       0
mobile_per_100            0
imf_program_active        0
key_events                0
remittances_gdp_pct       0
exports_gdp_pct           0
imports_gdp_pct           0
fdi_gdp_pct               0
gdp_growth_category       0
inflation_category        0
decade                    0
dtype: int64

In [255]:
# for percentage of missing values per column
df.isna().mean() * 100

year                      0.0
gdp_usd_bn                0.0
gdp_growth_pct            0.0
gdp_per_capita_usd        0.0
inflation_cpi_pct         0.0
unemployment_pct          0.0
remittances_usd_bn        0.0
exports_usd_bn            0.0
imports_usd_bn            0.0
trade_balance_usd_bn      0.0
forex_reserves_usd_bn     0.0
policy_rate_pct           0.0
pkr_per_usd               0.0
public_debt_gdp_pct       0.0
current_account_usd_bn    0.0
fdi_inflows_usd_bn        0.0
population_mn             0.0
literacy_rate_pct         0.0
agriculture_gdp_pct       0.0
services_gdp_pct          0.0
industry_gdp_pct          0.0
tax_revenue_gdp_pct       0.0
mobile_per_100            0.0
imf_program_active        0.0
key_events                0.0
remittances_gdp_pct       0.0
exports_gdp_pct           0.0
imports_gdp_pct           0.0
fdi_gdp_pct               0.0
gdp_growth_category       0.0
inflation_category        0.0
decade                    0.0
dtype: float64

In [256]:
# return just one boolean per row
df.isna().any()

year                      False
gdp_usd_bn                False
gdp_growth_pct            False
gdp_per_capita_usd        False
inflation_cpi_pct         False
unemployment_pct          False
remittances_usd_bn        False
exports_usd_bn            False
imports_usd_bn            False
trade_balance_usd_bn      False
forex_reserves_usd_bn     False
policy_rate_pct           False
pkr_per_usd               False
public_debt_gdp_pct       False
current_account_usd_bn    False
fdi_inflows_usd_bn        False
population_mn             False
literacy_rate_pct         False
agriculture_gdp_pct       False
services_gdp_pct          False
industry_gdp_pct          False
tax_revenue_gdp_pct       False
mobile_per_100            False
imf_program_active        False
key_events                False
remittances_gdp_pct       False
exports_gdp_pct           False
imports_gdp_pct           False
fdi_gdp_pct               False
gdp_growth_category       False
inflation_category        False
decade                    False
dtype: bool

### Dealing with missing values

In [257]:
df.shape

(26, 32)

In [258]:
# drop any row that has even one missing value
df.dropna()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [259]:
df.shape

(26, 32)

In [260]:
# drop any column that has even one missing value   
df.dropna(axis=1)

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [261]:
# drop rows where you have 3 missing values at least
df.dropna(thresh=3)
# just do axis=1 for columns

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [262]:
# only check specific columns for missing values
df.dropna(subset=["gdp_growth_category", "decade"])

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [263]:
# Instead of deleting, you can also just try to fill in the missing values btw
df.fillna("NA")

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [264]:
# you can just fill the missing value with the mean, median, or mode of the respective column that missing value is in
df["gdp_usd_bn"].fillna(df["gdp_usd_bn"].mean())

0      99.9
1     101.4
2     107.6
3     116.3
4     126.7
5     137.4
6     152.4
7     168.0
8     192.5
9     173.6
10    177.1
11    222.2
12    239.6
13    247.1
14    270.6
15    271.1
16    282.5
17    305.0
18    314.6
19    263.7
20    263.2
21    348.7
22    376.5
23    337.9
24    374.6
25    390.0
Name: gdp_usd_bn, dtype: float64

In [265]:
# fill the missing value with the value of that same column from the previous row, this is mostly used in time series data
df.ffill()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [266]:
# the opposite of ffill
df.bfill()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

## Type Casting

- we generally care about two types of variables, numeric or categorical, and if categorical columns are type cast as strings, then we should probably turn them into a float or int

In [267]:
df["gdp_usd_bn"].dtype

dtype('float64')

In [268]:
df["gdp_usd_bn"].astype("int")

0      99
1     101
2     107
3     116
4     126
5     137
6     152
7     168
8     192
9     173
10    177
11    222
12    239
13    247
14    270
15    271
16    282
17    305
18    314
19    263
20    263
21    348
22    376
23    337
24    374
25    390
Name: gdp_usd_bn, dtype: int64

## Duplicates

- same stuff as missing values, find them, and then deal with them, we can remove them simply and choose which to keep

In [269]:
# same pattern as isna
df.duplicated()
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [year, gdp_usd_bn, gdp_growth_pct, gdp_per_capita_usd, inflation_cpi_pct, unemployment_pct, remittances_usd_bn, exports_usd_bn, imports_usd_bn, trade_balance_usd_bn, forex_reserves_usd_bn, policy_rate_pct, pkr_per_usd, public_debt_gdp_pct, current_account_usd_bn, fdi_inflows_usd_bn, population_mn, literacy_rate_pct, agriculture_gdp_pct, services_gdp_pct, industry_gdp_pct, tax_revenue_gdp_pct, mobile_per_100, imf_program_active, key_events, remittances_gdp_pct, exports_gdp_pct, imports_gdp_pct, fdi_gdp_pct, gdp_growth_category, inflation_category, decade]
Index: []

[0 rows x 32 columns]

### Dealing with duplicates

In [270]:
df.drop_duplicates()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [271]:
# drop duplicates from specific columns
df.drop_duplicates(subset=["gdp_usd_bn"])
# keep last occurence from the duplicates rows
df.drop_duplicates(keep="last")

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

## Feature Engineering (make new derived columns)

- feature engineering is inventing new data from existing data, like multiple length of width to get area etc. You have 2 simple ways of doing it, just do direct maths on columns and get a new column or make a custom function and use .apply to use it

In [273]:
# Simple addition
df['export_import_pct'] = df['exports_gdp_pct'] + df['imports_gdp_pct']
# Combining text columns
# going to kep this commented out since it will throw an error
# df['full_name'] = df['first_name'] + ' ' + df['last_name']

In [274]:
def double_gdp(gdp):
    return gdp * 2

df["double_gdp"] = df["gdp_usd_bn"].apply(double_gdp)
summary_df = df.groupby('year').agg({
    'gdp_usd_bn': ['mean', 'max'],
})
summary_df

     gdp_usd_bn
           mean    max
year
2000       99.9   99.9
2001      101.4  101.4
2002      107.6  107.6
2003      116.3  116.3
2004      126.7  126.7
2005      137.4  137.4
2006      152.4  152.4
2007      168.0  168.0
2008      192.5  192.5
2009      173.6  173.6
2010      177.1  177.1
2011      222.2  222.2
2012      239.6  239.6
2013      247.1  247.1
2014      270.6  270.6
2015      271.1  271.1
2016      282.5  282.5
2017      305.0  305.0
2018      314.6  314.6
2019      263.7  263.7
2020      263.2  263.2
2021      348.7  348.7
2022      376.5  376.5
2023      337.9  337.9
2024      374.6  374.6
2025      390.0  390.0

In [276]:
# pivot_table is a bit complicated. 
# the first arg it takes in is index, this will become the vertical axis at the start of each row
# the second param is values, which is what you wanna calc, by default, it will just fine mean and nothing else
df1 = df.pivot_table(index="key_events", values="gdp_usd_bn")
df1

                               gdp_usd_bn
key_events
9/11 impact + debt relief           101.4
COVID-19 pandemic                   263.2
CPEC investment peak                305.0
CPEC launch                         270.6
Commodity price fall                271.1
Debt restructuring                  222.2
Economic reform start               107.6
Floods recovery                     177.1
Global commodity boom               168.0
Global financial crisis             192.5
Growth acceleration                 116.3
Growth recovery                     282.5
Growth slowdown                     152.4
High growth period                  126.7
IMF bailout + PKR crash             337.9
IMF bailout + floods                173.6
IMF program + energy crisis         239.6
IMF stabilization                   263.7
Political transition                247.1
Post-COVID rebound                  348.7
Post-sanctions recovery              99.9
Record growth 8.6%                  137.4
Record inflation + floods           376.5
Recovery + record remittances       390.0
Stabilization + disinflation        374.6
Twin deficits crisis                314.6

In [277]:
# if you don't want mean and want something else, you can use aggfunc
df1 = df.pivot_table(index="key_events", values="gdp_usd_bn", aggfunc="sum")
df1

                               gdp_usd_bn
key_events
9/11 impact + debt relief           101.4
COVID-19 pandemic                   263.2
CPEC investment peak                305.0
CPEC launch                         270.6
Commodity price fall                271.1
Debt restructuring                  222.2
Economic reform start               107.6
Floods recovery                     177.1
Global commodity boom               168.0
Global financial crisis             192.5
Growth acceleration                 116.3
Growth recovery                     282.5
Growth slowdown                     152.4
High growth period                  126.7
IMF bailout + PKR crash             337.9
IMF bailout + floods                173.6
IMF program + energy crisis         239.6
IMF stabilization                   263.7
Political transition                247.1
Post-COVID rebound                  348.7
Post-sanctions recovery              99.9
Record growth 8.6%                  137.4
Record inflation + floods           376.5
Recovery + record remittances       390.0
Stabilization + disinflation        374.6
Twin deficits crisis                314.6

## Merging dfs and mapping a column to labels

- mapping a column to a label is simply making a mapper (just a dictionary) and in that dict, you map the values of a column to a certain label, then you use .map on the df with that column selected
- merging tables is more or less the same as sql joins, you have a foreign key, and you have the type of join, inner or left or right or outer etc

In [278]:
mapper = {0: "not_under_IMF_plan", 1: "under_IMF_plan"}

df["imf_program_active"] = df["imf_program_active"].map(mapper)
df.head()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade,export_import_pct,double_gdp
0,2000,99.9,3.9,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s,19.52,199.8
1,2001,101.4,2.0,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s,19.82,202.8
2,2002,107.6,3.1,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s,19.42,215.2
3,2003,116.3,4.7,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s,20.55,232.6
4,2004,126.7,7.4,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s,23.28,253.4

In [280]:
# we can basically do sql joins using merge
df2 = {"year": 2025, "dummy_column": 400}
df2 = pd.DataFrame(df2, index=[0])

merged_df = pd.merge(df, df2, on="year", how="left")

In [282]:
merged_df

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade,export_import_pct,double_gdp,dummy_column
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s,19.52,199.8,NaN
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,1.44,9.66,10.16,0.37,Low Growth,Low,2000s,19.82,202.8,NaN
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s,19.42,215.2,NaN
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s,20.55,232.6,NaN
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s,23.28,253.4,NaN
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s,30.50,274.8,NaN
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s,32.21,304.8,NaN
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s,27.44,336.0,NaN
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s,31.33,385.0,NaN
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s,29.55,347.2,NaN
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,5.03,10.90,19.59,1.14,Low Growth,High,2010s,30.49,354.2,NaN
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s,30.78,444.4,NaN
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s,28.76,479.2,NaN
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s,28.25,494.2,NaN
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s,26.83,541.2,NaN
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s,24.68,542.2,NaN
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s,22.69,565.0,NaN
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s,23.21,610.0,NaN
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s,27.24,629.2,NaN
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s,25.44,527.4,NaN
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s,25.46,526.4,NaN
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s,29.97,697.4,NaN
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,7.18,8.61,21.25,0.51,High Growth,High,2020s,29.86,753.0,NaN
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s,24.57,675.8,NaN
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s,22.48,749.2,NaN
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s,23.59,780.0,400.0

In [283]:
df2.head()

   year  dummy_column
0  2025           400